title: Piotr Wójcik, English Editor
email: piotr.edit@gmail.com
description: "Profesjonalna korekta angielskiego od native'a"

remote_theme: y7kim/agency-jekyll-theme

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/pioioiotr
