remote_theme: b2a3e8/jekyll-theme-console
header_pages:
  - index.md
  - about.md
  - work.md
footer: 'please reach out via [email](mailto:pwojcik606@gmail.com) or [twitter](https://twitter.com/pioioiotr). i'm also on [linkedin](https://www.linkedin.com/in/piotr-wojcik-chicago/).'
