remote_theme: b2a3e8/jekyll-theme-console
header_pages:
  - index.md
  - about.md
  - work.md
  - tracks-traces.md
title: piotr wojcik
footer: please reach out via <a href="mailto:pwojcik606@gmail.com">email</a> or <a href="https://www.linkedin.com/in/pioioiotr">linkedin</a>.
